name: Deploy to VPS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        echo "=== Current directory ==="
        pwd
        echo "=== Files in directory ==="
        ls -la
        echo "=== Requirements files ==="
        find . -name "requirements*.txt"
        echo "=== Content of requirements.txt ==="
        cat requirements.txt
        echo "=== Installing requirements ==="
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short
      env:
        BOT_TOKEN: "test_token_12345"
        WEATHER_API_KEY: "test_api_key_67890"
        DATABASE_URL: sqlite:///test.db

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t weather-bot:${{ github.sha }} .
        docker tag weather-bot:${{ github.sha }} weather-bot:latest
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /root/tg_weather_bot/weather_bot
          git pull origin main
          docker-compose down
          docker-compose up -d --build
          docker system prune -f
          echo "✅ Развертывание завершено!" 