name: Deploy to VPS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        DATABASE_URL: sqlite:///test.db

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build -t chipekve/weather-bot:${{ github.sha }} .
        docker tag chipekve/weather-bot:${{ github.sha }} chipekve/weather-bot:latest
        docker push chipekve/weather-bot:${{ github.sha }}
        docker push chipekve/weather-bot:latest
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /root/tg_weather_bot/weather_bot
          git pull origin main
          docker-compose down
          docker pull chipekve/weather-bot:latest
          docker-compose up -d
          docker system prune -f
          echo "✅ Развертывание завершено!" 
